import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { Button } from '@/components/Buttons'

export default function Home() {
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className='main'>
        <p >Hola parrafo 1 lo suficientemente largo para que pase algo distinto ajhskjhakljh kjhkjh kjhk</p>
        <Button
          onClick={() => console.log('click')}
          title='Click me'
          styleType='secondary'
        />
      </main>
    </>
  )
}
